export const ResponseMessage = {
    CREATE_DATE_SUCCESS: "Tạo giờ thành công",
    LOGIN_SUCCESS: "Đăng nhập thành công",
    USER_NOT_EXIST: "Người dùng không tồn tại",
    LOGIN_FAILED: "Đăng nhập thất bại",
    SIGN_UP_SUCCESS: "Đăng kí thành công link xác thực đã được gửi vể gmail của bạn",
    GET_USER_BALANCE_SUCCESS: "Lấy thông tin số dư tài khoản thành công",
    GET_USER_DETAIL_SUCCESS: "Lấy thông tin người dùng thành công",
    START_VMS_SUCCESS: "Khời động VMS thành công",
    STOP_VMS_SUCCESS: "Dừng VMS thành công",
    REBOOT_VMS_SUCCESS: "Khởi động lại vms thành công",
    DESTROY_VMS_SUCCESS: "Xóa vms thành công",
    RESET_VMS_SUCCESS: "Reset vms thành công",
    SHUTDOWN_VMS_SUCCESS: "Tắt vms thành công",
    SHUTDOWN_VMS_FAILED: "Tắt vms thất bại",
    START_VMS_FAILED: "Khời động VMS thất bại",
    UPDATE_VMS_SUCCESS: "Cập nhật vms thành công",
    UPDATE_SERVICE_LABEL_SUCCESS: "Cập nhật service label thành công",
    GET_ACTION_HISTORY_SUCCES: "Lấy lịch sử thao tác thành công",
    LOGIN_FAILED_ACCOUNT_NOT_VERIFY: "Tài khoản chưa được xác thực vui lòng kiểm tra email",
    SIGN_UP_FAILED_EMAIL_EXIST: "Đăng kí thất bại email đã tồn tại",
    SIGN_UP_FAILED_PHONE_NUMBER_EXIST: "Đăng kí thất bại số điện thoại đã tồn tại",
    SIGN_UP_FAILED_EMPLOYMENT_EXIST: "Đăng kí thất bại mã số nhân viên đã tồn tại",

}